[versions]
activity-compose = "1.11.0"
androidx-junit = "1.3.0"
appcompat = "1.7.1"
core-ktx = "1.17.0"
espresso-core = "3.7.0"
junit = "4.13.2"
lifecycle-runtime-ktx = "2.9.4"
androidxComposeBom = "2025.11.00"
kotlin-android = "2.2.21"
androidGradlePlugin = "8.13.0"
vaniktech-plugin="0.34.0"
kotlinStdlib = "2.2.21"
kotlinTest = "2.2.21"
runner = "1.7.0"
core = "1.7.0"
compose = "1.9.3"
uiTestJunit4 = "1.9.4"
composeMultiplatform = "1.9.1"
[libraries]
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
compose-desktop = { module = "org.jetbrains.compose.desktop:desktop", version.ref = "compose" }
material = { module = "org.jetbrains.compose.material:material", version.ref = "compose" }
material-icons-core = { module = "org.jetbrains.compose.material:material-icons-core", version = "1.7.3" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose"}
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui = {group="androidx.compose.ui",name="ui"}
androidx-compose-ui-graphics = {group="androidx.compose.ui",name="ui-graphics"}
androidx-compose-material3 = { group="androidx.compose.material3",name ="material3"}
androidx-compose-ui-tooling-preview = {group="androidx.compose.ui",name="ui-tooling-preview"}
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlinTest" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "core" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "uiTestJunit4" }
[plugins]
androidx-kotlin = {id="org.jetbrains.kotlin.android",version.ref="kotlin-android"}
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-android" }
vanniktech-plugin = { id = "com.vanniktech.maven.publish",version.ref="vaniktech-plugin"}
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin-android" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }

android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }
android-lint = { id = "com.android.lint", version.ref = "androidGradlePlugin" }
[bundles]

